server:
  port: 9527

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600

      routes:
        - id: path_route  #权限
          uri:  http://localhost:8081
          predicates:
            - Path=/auth-server/**
            #filters:
            #- StripPrefix=1
        - id: docs_server
          uri: http://localhost:8002
          predicates:
            - Path=/docs/**

        - id: file_manage
          uri: http://localhost:8001
          predicates:
            - Path=/file/**

        - id: docs_share
          uri: http://localhost:8004
          predicates:
            - Path=/share/**,/insertShare,/deleteShare,/saveFile

        - id: calendar_manage
          uri: http://localhost:8085
          predicates:
            - Path=/calendarManage/**

        - id: search
          uri: http://localhost:9001
          predicates:
            - Path=/search/**
