
spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ****
    url: jdbc:mysql://localhost:3306/easystudyplatform?useUnicode=true&characterEncoding=utf-8


mybatis:
  config-location: classpath:config/sqlMapConfig.xml
  mapper-locations: classpath:mapper/*Mapper.xml

server:
  port: 8085

